### ISSUE TITLE
Issue Related to License and Code-Of-Conduct

### ISSUE THREAD

**Issue by iamwatchdogs** [suman-shah/c-program-example#101]
# Issue Related to License and Code-Of-Conduct

## Introduction:
Hi, There @suman-shah, I would love to contribute to this Repo on the occasion of hacktoberfest.
But this Repo is missing two of the crucial files required for collaboration/contribution.
This Repo is missing the "**LICENSE**" file and "**CODE_OF_CONDUCT.md**" file which provides licensing of the Repo allowing us to contribute to it legally.

## Reference:
This is mentioned in the guide for contribution provided by GitHub itself. Once check it out down here,
- [A checklist before you contribute](https://opensource.guide/how-to-contribute/#a-checklist-before-you-contribute).
- [Anatomy of an open source project](https://opensource.guide/how-to-contribute/#anatomy-of-an-open-source-project).
- [Establishing a code of conduct](https://opensource.guide/code-of-conduct/).
- [A Code of Conduct for Open Source Communities](https://www.contributor-covenant.org/).

## Solution:
- [ ] Create a file name "LICENSE" and another name "CODE_OF_CONDUCT.md".
- [ ] Copy the licensing content into the "LICENSE" file. *( You can select it from [choosealicense.com](https://choosealicense.com/), I would suggest [MIT License](https://choosealicense.com/licenses/mit/) )*
- [ ] Copy the Code-Of-Conduct content into. *( You can select it from [contributor-covenant](https://www.contributor-covenant.org/), I would suggest [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md) )*
- [ ] Save & Push the changes in the Repo.

---

### Note:
If you can do it by yourself then it is fine, or If you want me to deal with this you can just assign me to this issue and I'll be working on it as soon as possible.

---

**Comment by suman-shah** [comment]
Go ahead brother 🙂

**Comment by iamwatchdogs** [comment]
Great, I'll be working on it

**Comment by iamwatchdogs** [comment]
@suman-shah I have done my job.
Review and Merge the PRs.

**Comment by iamwatchdogs** [comment]
PRs #103, #104 closes #101 issue
